version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: dms_db
      POSTGRES_USER: dms_user
      POSTGRES_PASSWORD: dms_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dms_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - dms_network

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    networks:
      - dms_network

  django:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
    networks:
      - dms_network
    env_file:
      - .env

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    networks:
      - dms_network

volumes:
  postgres_data:

networks:
  dms_network:
    driver: bridge
