# Generated by Django 5.2 on 2025-04-29 06:57

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='documents/'),
        ),
    ]
